# Generated by Django 4.1.4 on 2023-02-05 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('tel', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=1)),
                ('carreer', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('g_name', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=50)),
                ('g_models', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('Net', models.IntegerField(default=0)),
                ('product', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('cid', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('gc_name', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(default=datetime.date(2023, 2, 5)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=50)),
                ('cid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OderDetails',
            fields=[
                ('did', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('gid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goods')),
                ('oid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='g_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goodscategory'),
        ),
    ]
