# Generated by Django 4.1.4 on 2023-02-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_customer_goods_goodscategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer12',
            fields=[
                ('cid', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=35)),
                ('surname', models.CharField(default='', max_length=35)),
                ('address', models.CharField(default='', max_length=200)),
                ('telephone', models.CharField(default='', max_length=10)),
                ('gender', models.BooleanField(default=True)),
                ('carreer', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goods12',
            fields=[
                ('gid', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=35)),
                ('brand', models.CharField(default='', max_length=35)),
                ('model', models.CharField(default='', max_length=35)),
                ('price', models.FloatField(default=0.0)),
                ('Net', models.IntegerField(default=0)),
                ('property', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory12',
            fields=[
                ('id', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('gc_name', models.CharField(default='', max_length=35)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OderDetails12',
            fields=[
                ('id', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goods12')),
            ],
        ),
        migrations.CreateModel(
            name='Order12',
            fields=[
                ('oid', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=50)),
                ('customer12', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customer12')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='g_category',
        ),
        migrations.RemoveField(
            model_name='oderdetails',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='oderdetails',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cid',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
        migrations.DeleteModel(
            name='OderDetails',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='oderdetails12',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.order12'),
        ),
        migrations.AddField(
            model_name='goods12',
            name='goodscategory12',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goodscategory12'),
        ),
    ]
