# Generated by Django 4.1.4 on 2023-02-05 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_customer12_goods12_goodscategory12_oderdetails12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(default=datetime.date(2023, 2, 6)),
        ),
        migrations.AlterField(
            model_name='order12',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 6)),
        ),
        migrations.AlterField(
            model_name='order12',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
